Upgrade from 0.9.6 to 0.11.15
Image went from quay.io/azavea/terraform:0.9.6
to quay.io/azavea/terraform:0.9.11 first with plan and apply.

Needed to skip 0.10 because none of the images we have our up to date on certs, luckily it
let us.

Worked around the following errros:
Error: aws_cloudfront_distribution.tilegarden: "cache_behavior": [REMOVED] Use `ordered_cache_behavior` configuration block(s) instead
Error: aws_route53_zone.internal: "vpc_id": [REMOVED] use 'vpc' configuration block instead
Error: aws_route53_zone.internal: "vpc_region": [REMOVED] use 'vpc' configuration block instead

Large list of changes to go to 0.11.5 mostly just new defaults. Did cause restart of site containers (~3 mins downtime..)